# Generated by Django 5.1.6 on 2025-03-06 12:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
