# Generated by Django 5.1.4 on 2025-01-20 07:11

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['uploaded_at']},
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(upload_to=courses.models.resource_upload_path),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to=courses.models.video_upload_path),
        ),
    ]
