# Generated by Django 5.1.4 on 2025-01-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_course_enrolled_students_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
