# Generated by Django 5.1.5 on 2025-01-30 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_resource_download_count_video_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoprogress',
            options={'verbose_name': 'Video Progress', 'verbose_name_plural': 'Video Progress'},
        ),
    ]
