# Generated by Django 5.1.6 on 2025-02-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_videoprogress_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('word', 'Word Document'), ('powerpoint', 'PowerPoint Presentation'), ('excel', 'Excel Spreadsheet'), ('link', 'Link')], default='pdf', max_length=50),
        ),
    ]
