# Generated by Django 5.1.7 on 2025-03-13 19:39

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_resource_resource_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=courses.models.course_image_upload_path),
        ),
    ]
