# Generated by Django 5.1.7 on 2025-03-15 07:04

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_course_options_alter_course_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=courses.models.video_thumbnail_upload_path),
        ),
    ]
