# Generated by Django 5.1.4 on 2025-01-23 03:37

import userauths.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0004_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='user_folder/default-user.jpg', null=True, upload_to=userauths.models.profile_image_upload_path),
        ),
    ]
