# Generated by Django 5.1.6 on 2025-03-09 05:59

import userauths.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0006_user_otp_user_otp_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='user_folder/default_profImg.png', null=True, upload_to=userauths.models.profile_image_upload_path),
        ),
    ]
