# Generated by Django 5.1.7 on 2025-03-14 20:36

import userauths.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0007_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=userauths.models.profile_image_upload_path),
        ),
    ]
