# Generated by Django 5.1.6 on 2025-03-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='video_position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
